### ISSUE TITLE
quitting a buffer

### ISSUE THREAD

**Issue by DerWeh** [rliang/termedit.nvim#1]
If I have the `terminal` in a split buffer and then invoke `EDITOR` closing it via `:q` or `ZQ` will also close the splitted window. `:TermRelese` on the other hand will not touch my other windows, but just close the editor and drop back into the terminal.

**Comment by rliang** [comment]
Sounds like an issue with vim's `:q`'s behavior. I use https://github.com/moll/vim-bbye to get around it.
